#!/bin/bash
source ../config/env
echo "Setting up vim"

#install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
       
cat "$CONFIG/.vimrc" > ~/.vimrc

vim ~/.vimrc +PluginInstall +qall
python3 ~/.vim/plugged/youcompleteme/install.py --all
